// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiWAkxZQ8td12RGrcStjTXe5Se9lqWyXc',
    appId: '1:1030341740474:web:7128f2009316c1246a3f83',
    messagingSenderId: '1030341740474',
    projectId: 'ui-sample-7b805',
    authDomain: 'ui-sample-7b805.firebaseapp.com',
    storageBucket: 'ui-sample-7b805.appspot.com',
    measurementId: 'G-2C3HEXTQJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4MJN6vAD8ScO87j_lg7-uJPh_yZcxLdk',
    appId: '1:1030341740474:android:749b3dc09a94fabc6a3f83',
    messagingSenderId: '1030341740474',
    projectId: 'ui-sample-7b805',
    storageBucket: 'ui-sample-7b805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm7qFXK5DEnUfphrUjAsP_CLbKxD1_zKg',
    appId: '1:1030341740474:ios:5f9bd6769c7d66aa6a3f83',
    messagingSenderId: '1030341740474',
    projectId: 'ui-sample-7b805',
    storageBucket: 'ui-sample-7b805.appspot.com',
    iosClientId: '1030341740474-rphijvpetudtjlepvvomuc69ipe19fl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm7qFXK5DEnUfphrUjAsP_CLbKxD1_zKg',
    appId: '1:1030341740474:ios:5f9bd6769c7d66aa6a3f83',
    messagingSenderId: '1030341740474',
    projectId: 'ui-sample-7b805',
    storageBucket: 'ui-sample-7b805.appspot.com',
    iosClientId: '1030341740474-rphijvpetudtjlepvvomuc69ipe19fl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiSample',
  );
}
